# Generated by Django 5.2 on 2025-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryschedule',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In-Transit', 'In-Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
