# Generated by Django 5.2 on 2025-05-18 14:08

from django.db import migrations

def update_status_values(apps, schema_editor):
    DeliverySchedule = apps.get_model('delivery', 'DeliverySchedule')
    # Update any existing records with old status values
    DeliverySchedule.objects.filter(status='In Progress').update(status='In-Transit')
    DeliverySchedule.objects.filter(status='Completed').update(status='Delivered')

class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliveryschedule_status'),
    ]

    operations = [
        migrations.RunPython(update_status_values),
    ]
