# Generated by Django 5.2 on 2025-05-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20250518_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='client_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='unit_info',
            field=models.JSONField(default=dict),
        ),
    ]
