# Generated by Django 5.2 on 2025-05-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliveryrequest_client_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='client_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='unit_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
