# Generated by Django 5.2 on 2025-05-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='client_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
