# Generated by Django 5.2 on 2025-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouseorder_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorderitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouseorderitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
