# Generated by Django 5.2 on 2025-05-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouseorderitem_item_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='client_company',
        ),
    ]
