# Generated by Django 5.2.1 on 2025-08-24 05:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_deliveryrequest_client_info_and_more'),
        ('warehouse', '0006_warehouseclientrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseclientrecord',
            options={'ordering': ['-last_order_date']},
        ),
        migrations.AddField(
            model_name='warehouseclientrecord',
            name='delivery_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryschedule'),
        ),
        migrations.AddField(
            model_name='warehouseclientrecord',
            name='last_order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseclientrecord',
            name='warehouse_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouseorder'),
        ),
        migrations.AlterField(
            model_name='warehouseclientrecord',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouseclientrecord',
            name='total_orders',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
