# Generated by Django 5.2 on 2025-04-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('work_shift', models.CharField(max_length=100)),
                ('employee_status', models.CharField(max_length=100)),
                ('employee_type', models.CharField(max_length=100)),
                ('temporary_password', models.CharField(max_length=100)),
            ],
        ),
    ]
