# Generated by Django 5.2 on 2025-04-26 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_userprofile_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_joining',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
