# Generated by Django 5.2 on 2025-05-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_userprofile_date_of_joining'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Heavy Equipment', 'Heavy Equipment'), ('Spare Parts', 'Spare Parts')], max_length=50)),
                ('unit_item', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('supplier', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('date_received', models.DateField()),
                ('status', models.CharField(choices=[('Low Stock', 'Low Stock'), ('In Stock', 'In Stock')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inventory_photos/')),
            ],
        ),
    ]
