# Generated by Django 5.2 on 2025-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_inventoryitem_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='status',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.CharField(choices=[('Warehouse', 'Warehouse'), ('Sales', 'Sales')], default='Warehouse', max_length=50),
            preserve_default=False,
        ),
    ]
