# Generated by Django 5.2 on 2025-05-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0006_alter_deliveryrequest_client_info_and_more'),
        ('sales', '0009_invoice_client_record_salesorder_client_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=20, unique=True)),
                ('unit_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('warranty_start', models.DateField()),
                ('warranty_end', models.DateField()),
                ('status', models.CharField(choices=[('Warranty Active', 'Warranty Active'), ('Warranty Expired', 'Warranty Expired'), ('No Warranty', 'No Warranty')], default='Warranty Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='delivery.deliveryschedule')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='sales.invoice')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='sales.salesorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
