# Generated by Django 5.2 on 2025-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('maintenance_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=20)),
                ('unit_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('assigned_tech', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
