# Generated by Django 5.2 on 2025-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0002_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='findings_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='reported_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='work_performed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
