# Generated by Django 5.2 on 2025-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0003_maintenancerecord_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='assigned_tech',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='technicians',
            field=models.ManyToManyField(blank=True, to='aftersales.technician'),
        ),
    ]
