# Generated by Django 5.2 on 2025-05-20 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0004_technician_remove_maintenancerecord_assigned_tech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='aftersales.servicerecord'),
        ),
    ]
