# Generated by Django 5.2 on 2025-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0005_maintenancerecord_service_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='usage_unit',
            field=models.CharField(default='km', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='usage_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='warranty_type',
            field=models.CharField(choices=[('Dump Truck', 'Dump Truck'), ('Heavy Equipment', 'Heavy Equipment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
