# Generated by Django 5.2 on 2025-05-18 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0007_requestnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.CharField(max_length=20, unique=True)),
                ('inspection_type', models.CharField(choices=[('PDI', 'Pre-Delivery Inspection'), ('Repair', 'Repair Inspection'), ('Maintenance', 'Maintenance Inspection')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Needs Recheck', 'Needs Recheck'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('department', models.CharField(default='Motorpool', max_length=100)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('unit_code', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100)),
                ('usage_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(choices=[('Bay 1', 'Motorpool Bay 1'), ('Bay 2', 'Motorpool Bay 2'), ('Bay 3', 'Motorpool Bay 3'), ('Workshop', 'Main Workshop'), ('Field', 'Field Location')], max_length=50)),
                ('checklist_reference', models.FileField(blank=True, null=True, upload_to='inspection_checklists/')),
                ('inspection_result', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20, null=True)),
                ('issues_found', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('spare_parts_used', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('inspection_photos', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('signed_form', models.FileField(blank=True, null=True, upload_to='inspection_forms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_inspections', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='sales.request')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
