# Generated by Django 5.2 on 2025-05-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Not Started'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Needs Recheck', 'Needs Recheck'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='', max_length=20),
        ),
    ]
