# Generated by Django 5.2 on 2025-05-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0002_alter_inspection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='technician',
        ),
        migrations.AddField(
            model_name='inspection',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
