# Generated by Django 5.2 on 2025-05-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0003_remove_inspection_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='department',
        ),
    ]
