# Generated by Django 5.2 on 2025-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0005_equipmentinspection_delete_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinspection',
            name='assigned_technician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
