# Generated by Django 5.2 on 2025-05-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0006_alter_equipmentinspection_assigned_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspection',
            name='checklist_reference',
            field=models.FileField(blank=True, null=True, upload_to='inspection_checklists/'),
        ),
    ]
