# Generated by Django 5.2 on 2025-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0007_equipmentinspection_checklist_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspection',
            name='assisted_by',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
