# Generated by Django 5.2 on 2025-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0008_equipmentinspection_assisted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspection',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinspection',
            name='inspection_result',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinspection',
            name='issues_found',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinspection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinspection',
            name='spare_parts_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
