# Generated by Django 5.2 on 2025-05-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0009_equipmentinspection_corrective_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspection',
            name='inspection_photos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinspection',
            name='signed_form',
            field=models.FileField(blank=True, null=True, upload_to='inspection_signed_forms/'),
        ),
    ]
