# Generated by Django 5.2.1 on 2025-05-23 12:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('pdi_request', 'PDI Request'), ('delivery_request', 'Delivery Request'), ('inspection_complete', 'Inspection Complete'), ('delivery_complete', 'Delivery Complete'), ('payment_received', 'Payment Received'), ('order_created', 'Order Created'), ('invoice_generated', 'Invoice Generated')], max_length=50)),
                ('from_department', models.CharField(choices=[('sales', 'Sales'), ('motorpool', 'Motorpool'), ('warehouse', 'Warehouse'), ('delivery', 'Delivery'), ('aftersales', 'Aftersales'), ('admin', 'Admin')], max_length=50)),
                ('to_department', models.CharField(choices=[('sales', 'Sales'), ('motorpool', 'Motorpool'), ('warehouse', 'Warehouse'), ('delivery', 'Delivery'), ('aftersales', 'Aftersales'), ('admin', 'Admin')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('related_link', models.CharField(blank=True, max_length=255)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
