# Generated by Django 5.2 on 2025-05-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
