# Generated by Django 5.2 on 2025-05-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_clientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.clientrecord'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='client_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.clientrecord'),
        ),
    ]
